// install-doc.mjs — the served /install.md page: MCP connection + skill install for
// the main clients, base URL interpolated from the live request origin. Built from an
// array of single-quoted lines so markdown backticks stay literal (no escaping).

export function renderInstall(base) {
  const L = [
    '# fix-ai-slop — install',
    '',
    'A remote **MCP** + REST design engine an LLM can call: it *judges* colors, fonts,',
    'spacing, radius, shadow, layout and motion for AI-slop, and *generates* fresh,',
    'gate-passing values — a whole coherent theme from one call. Closed-form math, no model.',
    '',
    '**Base URL:** `' + base + '`',
    '',
    'You need two pieces. Connect the **MCP** always; add the **skill** (or use a **prompt**)',
    'so the model follows the process instead of grabbing raw values.',
    '',
    '| Piece | What it is | Required? |',
    '|---|---|---|',
    '| MCP server | the 20 tools — the muscle | always |',
    '| fix-ai-slop skill *or* an MCP prompt | the process (which tool, when, the gates) — the judgment | strongly recommended |',
    '',
    '---',
    '',
    '## 1 · Connect the MCP',
    '',
    '### Claude Code',
    '```bash',
    'claude mcp add --transport http fix-ai-slop ' + base + '/mcp',
    '```',
    '',
    '### Cursor — `.cursor/mcp.json` (project) or `~/.cursor/mcp.json` (global)',
    '```json',
    '{',
    '  "mcpServers": {',
    '    "fix-ai-slop": { "url": "' + base + '/mcp" }',
    '  }',
    '}',
    '```',
    'Then **Settings → MCP → enable** and wait for the green dot.',
    '',
    '### Claude Desktop / any client that needs a stdio bridge',
    '```json',
    '{',
    '  "mcpServers": {',
    '    "fix-ai-slop": {',
    '      "command": "npx",',
    '      "args": ["mcp-remote", "' + base + '/mcp"]',
    '    }',
    '  }',
    '}',
    '```',
    '',
    '**Verify** (should list 20 tools):',
    '```bash',
    "curl -s -X POST " + base + "/mcp -H 'content-type: application/json' \\",
    '  -d \'{"jsonrpc":"2.0","id":1,"method":"tools/list"}\'',
    '```',
    '',
    '---',
    '',
    '## 2 · Install the process (the fix-ai-slop skill)',
    '',
    '`SKILL.md` is a **cross-agent standard** — the same skill works in Claude Code, Cursor,',
    'and Codex. It is **staggered**: a cheap `SKILL.md` index (~2 KB) loads, and each pass',
    '(`polish`, `colorize`, …) plus the full `design-law.md` load only on demand. Raw index:',
    '`' + base + '/skill/SKILL.md`',
    '',
    '### One line — Claude Code, Cursor, Codex',
    '```bash',
    'curl -fsSL ' + base + '/skill | sh',
    '```',
    'Writes `~/.claude/skills/fix-ai-slop/` (index + passes) and mirrors to `~/.agents/skills/`.',
    'Cursor and Codex read `~/.claude/skills/` for compatibility, so all three pick it up.',
    '',
    '### Invoke it',
    '- `/fix-ai-slop` — the full guide; the agent reads the index and runs whatever passes your',
    '  request needs, in order (one or several).',
    '- `/fix-ai-slop:polish` (or `:colorize`, `:typeset`, `:theme`, …) — jump straight to one pass.',
    '',
    '### Project-local (checked into a repo)',
    '```bash',
    'mkdir -p .cursor/skills/fix-ai-slop && curl -fsSL ' + base + '/skill/SKILL.md \\',
    '  -o .cursor/skills/fix-ai-slop/SKILL.md',
    '```',
    '',
    '---',
    '',
    '## 3 · No-install option — use a prompt',
    '',
    'The MCP exposes 7 prompts (`prompts/list`) that carry the same process:',
    '`explore` · `improve_design` · `design_review` · `theme` · `colorize` · `typeset` · `polish`.',
    'In a client that surfaces MCP prompts, pick one — no skill needed. Each embeds the full',
    'design law, so the tools stay guarded even without the skill installed.',
    '',
    '---',
    '',
    '## 4 · Use it',
    '',
    'Say: *"use fix-ai-slop to build me a landing page for X."*',
    'A working setup **asks you direction questions first**, then routes every deterministic',
    'decision to a tool. Two rules the engine enforces so AI designs stop breaking:',
    '- **Fonts:** `suggest_fonts` → `pairing.body` is the readable face; never a display font for body text.',
    '- **Layout:** use the `container` tokens from `layout`; never re-add margin on top of `inner`.',
    '',
    'Self-host, tool reference, and deploy notes live in the repo (`apps/DEPLOY.md`).',
    '',
  ];
  return L.join('\n') + '\n';
}
