// install-doc.mjs — the served /install.md page: MCP connection + skill install for
// the main clients, base URL interpolated from the live request origin. Built from an
// array of single-quoted lines so markdown backticks stay literal (no escaping).

export function renderInstall(base) {
  const L = [
    '# fixmyslop — install',
    '',
    'A remote **MCP** + REST design engine an LLM can call: it *judges* colors, fonts,',
    'spacing, radius, shadow, layout and motion for AI-slop, and *generates* fresh,',
    'gate-passing values — a whole coherent theme from one call. Closed-form math, no model.',
    '',
    '**Base URL:** `' + base + '`',
    '',
    'You need two pieces. Connect the **MCP** always; add the **skill** (or use a **prompt**)',
    'so the model follows the process instead of grabbing raw values.',
    '',
    '| Piece | What it is | Required? |',
    '|---|---|---|',
    '| MCP server | the live tool catalog — the muscle | always |',
    '| fixmyslop skill *or* an MCP prompt | the process (which tool, when, the gates) — the judgment | strongly recommended |',
    '',
    '---',
    '',
    '## 1 · Connect the MCP',
    '',
    '### Claude Code',
    '```bash',
    'claude mcp add --transport http fixmyslop ' + base + '/mcp',
    '```',
    '',
    '### Grok CLI',
    'Grok can register a remote Streamable HTTP server from the terminal:',
    '```bash',
    'grok mcp add --transport http fixmyslop ' + base + '/mcp',
    'grok mcp doctor fixmyslop',
    '```',
    'Or add the same server to `~/.grok/config.toml`:',
    '```toml',
    '[mcp_servers.fixmyslop]',
    'url = "' + base + '/mcp"',
    '```',
    '',
    '### Codex — `~/.codex/config.toml`',
    'Add the remote server to your Codex MCP configuration:',
    '```toml',
    '[mcp_servers.fixmyslop]',
    'url = "' + base + '/mcp"',
    '```',
    'Restart Codex, then check the MCP connection in the client UI.',
    '',
    '### Cursor — `.cursor/mcp.json` (project) or `~/.cursor/mcp.json` (global)',
    '```json',
    '{',
    '  "mcpServers": {',
    '    "fixmyslop": { "url": "' + base + '/mcp" }',
    '  }',
    '}',
    '```',
    'Then **Settings → MCP → enable** and wait for the green dot.',
    '',
    '### Windsurf — `~/.codeium/windsurf/mcp_config.json`',
    'Open **Settings → Manage MCPs → View raw config**, then add:',
    '```json',
    '{',
    '  "mcpServers": {',
    '    "fixmyslop": { "serverUrl": "' + base + '/mcp" }',
    '  }',
    '}',
    '```',
    'Some Windsurf builds label the same field `url`; use the field shown by your editor.',
    '',
    '### OpenCode — `opencode.json`',
    'Current OpenCode builds use `mcp.servers` for remote servers:',
    '```json',
    '{',
    '  "$schema": "https://opencode.ai/config.json",',
    '  "mcp": {',
    '    "servers": {',
    '      "fixmyslop": {',
    '        "type": "remote",',
    '        "url": "' + base + '/mcp"',
    '      }',
    '    }',
    '  }',
    '}',
    '```',
    'If your build supports the CLI helper:',
    '```bash',
    'opencode mcp add fixmyslop --url ' + base + '/mcp',
    'opencode mcp list',
    '```',
    'Older OpenCode builds use the pre-v2 schema; put the `fixmyslop` object directly under `mcp`.',
    '',
    '### VS Code / GitHub Copilot — `.vscode/mcp.json`',
    'Use **MCP: Add Server** or create the workspace file:',
    '```json',
    '{',
    '  "servers": {',
    '    "fixmyslop": {',
    '      "type": "http",',
    '      "url": "' + base + '/mcp"',
    '    }',
    '  }',
    '}',
    '```',
    '',
    '### Cline',
    'From the Cline CLI:',
    '```bash',
    'cline mcp add fixmyslop ' + base + '/mcp --type http',
    '```',
    'Or open Cline’s **MCP Servers** panel and add the same Streamable HTTP URL.',
    '',
    '### Claude Desktop / clients that need a stdio bridge',
    'For clients that cannot speak remote HTTP directly, use `mcp-remote`:',
    '',
    '```json',
    '{',
    '  "mcpServers": {',
    '    "fixmyslop": {',
    '      "command": "npx",',
    '      "args": ["mcp-remote", "' + base + '/mcp"]',
    '    }',
    '  }',
    '}',
    '```',
    '',
    '### xAI API (Grok Responses API)',
    'For programmatic Grok calls, add the remote MCP tool to the request’s `tools` array:',
    '```json',
    '{',
    '  "type": "mcp",',
    '  "server_url": "' + base + '/mcp",',
    '  "server_label": "fixmyslop"',
    '}',
    '```',
    'Use `server_label: "fixmyslop"` so tool calls are easy to identify; add `allowed_tools` to restrict the catalog.',
    '',
    'Client references: [Grok MCP](https://docs.x.ai/build/features/mcp-servers), [Cursor MCP](https://docs.cursor.com/context/model-context-protocol), [OpenCode MCP](https://opencode.ai/v2/docs/mcp-servers), [VS Code MCP](https://code.visualstudio.com/docs/agent-customization/mcp-servers), [Windsurf MCP](https://docs.windsurf.com/windsurf/cascade/mcp).',
    '',
    '**Verify** (should list the current catalog, including connected_style_genome, check_svg, and build_page):',
    '```bash',
    "curl -s -X POST " + base + "/mcp -H 'content-type: application/json' \\",
    '  -d \'{"jsonrpc":"2.0","id":1,"method":"tools/list"}\'',
    '```',
    '',
    '---',
    '',
    '## 2 · Install the process (the fixmyslop skill)',
    '',
    '`SKILL.md` is a **cross-agent standard** — the same skill works in Claude Code, Cursor,',
    'and Codex. It is **staggered**: a cheap `SKILL.md` index (~2 KB) loads, and each pass',
    '(`polish`, `colorize`, …) plus the full `design-law.md` load only on demand. Raw index:',
    '`' + base + '/skill/SKILL.md`',
    '',
    '### One line — Claude Code, Cursor, Codex',
    '```bash',
    'curl -fsSL ' + base + '/skill | sh',
    '```',
    'Writes `~/.claude/skills/fixmyslop/` (index + passes) and mirrors to `~/.agents/skills/`.',
    'Cursor and Codex read `~/.claude/skills/` for compatibility, so all three pick it up.',
    '',
    '### Invoke it',
    '- `/fixmyslop` — the full guide; the agent reads the index and runs whatever passes your',
    '  request needs, in order (one or several).',
    '- `/fixmyslop:polish` (or `:colorize`, `:typeset`, `:theme`, …) — jump straight to one pass.',
    '',
    '### Project-local (checked into a repo)',
    '```bash',
    'mkdir -p .cursor/skills/fixmyslop && curl -fsSL ' + base + '/skill/SKILL.md \\',
    '  -o .cursor/skills/fixmyslop/SKILL.md',
    '```',
    '',
    '---',
    '',
    '## 3 · No-install option — use a prompt',
    '',
    'The MCP exposes 7 prompts (`prompts/list`) that carry the same process:',
    '`explore` · `improve_design` · `design_review` · `theme` · `colorize` · `typeset` · `polish`.',
    'In a client that surfaces MCP prompts, pick one — no skill needed. Each embeds the full',
    'design law, so the tools stay guarded even without the skill installed.',
    '',
    '---',
    '',
    '## 4 · Use it',
    '',
    'Say: *"use fixmyslop to build me a landing page for X."*',
    'A working setup **asks you direction questions first**, then routes every deterministic',
    'decision to a tool. Two rules the engine enforces so AI designs stop breaking:',
    '- **Fonts:** `suggest_fonts` → `pairing.body` is the readable face; never a display font for body text.',
    '- **Layout:** use the `container` tokens from `layout`; never re-add margin on top of `inner`.',
    '',
    'Self-host, tool reference, and deploy notes live in the repo (`apps/DEPLOY.md`).',
    '',
  ];
  return L.join('\n') + '\n';
}
