// install-doc.mjs — the served /install.md page: MCP connection + skill install for
// the main clients, base URL interpolated from the live request origin. Built from an
// array of single-quoted lines so markdown backticks stay literal (no escaping).

export function renderInstall(base) {
  const L = [
    '# ai-slop-font — install',
    '',
    'A remote **MCP** + REST design engine an LLM can call: it *judges* colors, fonts,',
    'spacing, radius, shadow, layout and motion for AI-slop, and *generates* fresh,',
    'gate-passing values — a whole coherent theme from one call. Closed-form math, no model.',
    '',
    '**Base URL:** `' + base + '`',
    '',
    'You need two pieces. Connect the **MCP** always; add the **skill** (or use a **prompt**)',
    'so the model follows the process instead of grabbing raw values.',
    '',
    '| Piece | What it is | Required? |',
    '|---|---|---|',
    '| MCP server | the 20 tools — the muscle | always |',
    '| atelier skill *or* an MCP prompt | the process (which tool, when, the gates) — the judgment | strongly recommended |',
    '',
    '---',
    '',
    '## 1 · Connect the MCP',
    '',
    '### Claude Code',
    '```bash',
    'claude mcp add --transport http ai-slop-font ' + base + '/mcp',
    '```',
    '',
    '### Cursor — `.cursor/mcp.json` (project) or `~/.cursor/mcp.json` (global)',
    '```json',
    '{',
    '  "mcpServers": {',
    '    "ai-slop-font": { "url": "' + base + '/mcp" }',
    '  }',
    '}',
    '```',
    'Then **Settings → MCP → enable** and wait for the green dot.',
    '',
    '### Claude Desktop / any client that needs a stdio bridge',
    '```json',
    '{',
    '  "mcpServers": {',
    '    "ai-slop-font": {',
    '      "command": "npx",',
    '      "args": ["mcp-remote", "' + base + '/mcp"]',
    '    }',
    '  }',
    '}',
    '```',
    '',
    '**Verify** (should list 20 tools):',
    '```bash',
    "curl -s -X POST " + base + "/mcp -H 'content-type: application/json' \\",
    '  -d \'{"jsonrpc":"2.0","id":1,"method":"tools/list"}\'',
    '```',
    '',
    '---',
    '',
    '## 2 · Install the process (the atelier skill)',
    '',
    'The skill is self-contained. Raw file: `' + base + '/skill/SKILL.md`',
    '',
    '### Claude Code — one line',
    '```bash',
    'curl -fsSL ' + base + '/skill | sh',
    '```',
    'Writes `~/.claude/skills/atelier/SKILL.md`; it auto-activates from its description.',
    '',
    '### Cursor / other skill-capable clients',
    'Save the skill into your client\'s skills directory, keeping the `name:` / `description:`',
    'frontmatter intact:',
    '```bash',
    'curl -fsSL ' + base + '/skill/SKILL.md -o <your-skills-dir>/atelier/SKILL.md',
    '```',
    'Or just ask the agent: *"install the skill at ' + base + '/skill/SKILL.md into this',
    'editor\'s skill system, keeping its frontmatter."*',
    '',
    '---',
    '',
    '## 3 · No-install option — use a prompt',
    '',
    'The MCP exposes 6 prompts (`prompts/list`) that carry the same process:',
    '`improve_design` · `design_review` · `theme` · `colorize` · `typeset` · `polish`.',
    'In a client that surfaces MCP prompts, pick one — no skill needed. Each embeds the full',
    'design law, so the tools stay guarded even without the skill installed.',
    '',
    '---',
    '',
    '## 4 · Use it',
    '',
    'Say: *"use ai-slop-font (and the atelier skill) to build me a landing page for X."*',
    'A working setup **asks you direction questions first**, then routes every deterministic',
    'decision to a tool. Two rules the engine enforces so AI designs stop breaking:',
    '- **Fonts:** `suggest_fonts` → `pairing.body` is the readable face; never a display font for body text.',
    '- **Layout:** use the `container` tokens from `layout`; never re-add margin on top of `inner`.',
    '',
    'Self-host, tool reference, and deploy notes live in the repo (`apps/DEPLOY.md`).',
    '',
  ];
  return L.join('\n') + '\n';
}
