// Generated by textslopbench/export_web_summary.py. Do not hand-edit.
window.TEXTSLOP_SUMMARY = Object.freeze({
  "claimMutations": 40,
  "comparisonPolicy": "Identity is always reported. No composite score and no superiority claim.",
  "identityBaseline": true,
  "interventionCases": 36,
  "ownedFixtures": 12,
  "suite": "TextSlopBench/local-safety-suite",
  "version": "0.2.0"
});
